### ISSUE TITLE
panic in `TestRealtimeChannel_RTL5_Detach/RTL5b:_If_channel_state_is_FAILED,_return_error`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#575]
Seen during [this integration test run](https://github.com/ably/ably-go/actions/runs/3838265654/jobs/6534519168#step:6:194) (JSON, Go 1.19):

```
=== RUN   TestRealtimeChannel_RTL5_Detach/RTL5b:_If_channel_state_is_FAILED,_return_error
    realtime_channel_spec_integration_test.go:1409: 
        	Error Trace:	realtime_channel_spec_integration_test.go:1409
        	Error:      	Received unexpected error:
        	            	Gateway Timeout
        	Test:       	TestRealtimeChannel_RTL5_Detach/RTL5b:_If_channel_state_is_FAILED,_return_error
--- FAIL: TestRealtimeChannel_RTL5_Detach (36.75s)
    --- PASS: TestRealtimeChannel_RTL5_Detach/RTL5a:_If_channel_is_INITIALIZED_or_DETACHED,_do_nothing (6.61s)
    --- FAIL: TestRealtimeChannel_RTL5_Detach/RTL5b:_If_channel_state_is_FAILED,_return_error (30.15s)
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb40cf3]

goroutine 1760 [running]:
testing.tRunner.func1.2({0xcb49c0, 0x11f7e60})
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1396 +0x372
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1399 +0x5f0
panic({0xcb49c0, 0x11f7e60})
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:890 +0x262
github.com/ably/ably-go/ablytest.(*Sandbox).Close(0x0)
	/home/runner/work/ably-go/ably-go/ablytest/sandbox.go:[191](https://github.com/ably/ably-go/actions/runs/3838265654/jobs/6534519168#step:6:192) +0x73
github.com/ably/ably-go/ably_test.safeclose(0xc0006f1d40, {0xc000367620, 0x1, 0xc000367608?})
	/home/runner/work/ably-go/ably-go/ably/ably_test.go:49 +0x2a6
panic({0xcb49c0, 0x11f7e60})
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:890 +0x262
github.com/ably/ably-go/ablytest.(*Sandbox).KeyParts(...)
	/home/runner/work/ably-go/ably-go/ablytest/sandbox.go:216
github.com/ably/ably-go/ablytest.(*Sandbox).Key(...)
	/home/runner/work/ably-go/ably-go/ablytest/sandbox.go:220
github.com/ably/ably-go/ablytest.(*Sandbox).Options(0x0, {0x0, 0x0, 0x0})
	/home/runner/work/ably-go/ably-go/ablytest/sandbox.go:230 +0x6b
github.com/ably/ably-go/ably_test.TestRealtimeChannel_RTL5_Detach.func3(0xc0006f1d40)
	/home/runner/work/ably-go/ably-go/ably/realtime_channel_spec_integration_test.go:1413 +0x17d
testing.tRunner(0xc0006f1d40, 0xd8e328)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1446 +0x[217](https://github.com/ably/ably-go/actions/runs/3838265654/jobs/6534519168#step:6:218)
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1493 +0x75e
FAIL	github.com/ably/ably-go/ably	336.880s
?   	github.com/ably/ably-go/ably/internal/ablyutil	[no test files]
?   	github.com/ably/ably-go/ablytest	[no test files]
?   	github.com/ably/ably-go/examples	[no test files]
?   	github.com/ably/ably-go/examples/realtime/presence	[no test files]
?   	github.com/ably/ably-go/examples/realtime/pub-sub	[no test files]
?   	github.com/ably/ably-go/examples/rest/history	[no test files]
?   	github.com/ably/ably-go/examples/rest/presence	[no test files]
?   	github.com/ably/ably-go/examples/rest/publish	[no test files]
?   	github.com/ably/ably-go/examples/rest/stats	[no test files]
?   	github.com/ably/ably-go/examples/rest/status	[no test files]
?   	github.com/ably/ably-go/scripts/errors	[no test files]
FAIL
```

**Comment by sacOO7** [comment]
Internal link to gateway error related discussion -> https://ably-real-time.slack.com/archives/C030C5YLY/p1699224411576189

**Comment by sacOO7** [comment]
Fixed as a part of https://github.com/ably/ably-go/pull/621/commits/e383770ac1b40ae05fc937a143ecdf1df8e80a51
