### ISSUE TITLE
panic in `TestRealtimeConn_RTC8a_ExplicitAuthorizeWhileConnected`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#576]
Seen during [this integration test run](https://github.com/ably/ably-go/actions/runs/3838265654/jobs/6534518995#step:6:442) (msgpack, Go 1.18):

```
=== RUN   TestRealtimeConn_RTC8a_ExplicitAuthorizeWhileConnected
--- FAIL: TestRealtimeConn_RTC8a_ExplicitAuthorizeWhileConnected (30.20s)
panic: Gateway Timeout [recovered]
	panic: Gateway Timeout

goroutine 1304174 [running]:
testing.tRunner.func1.2({0xc71640, 0xc0002d2240})
	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1392 +0x5d2
panic({0xc71640, 0xc0002d2240})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:844 +0x258
github.com/ably/ably-go/ablytest.MustSandbox(0x38?)
	/home/runner/work/ably-go/ably-go/ablytest/sandbox.go:126 +0x72
github.com/ably/ably-go/ablytest.NewREST({0x0, 0x0, 0x0})
	/home/runner/work/ably-go/ably-go/ablytest/sandbox.go:115 +0x52
github.com/ably/ably-go/ably_test.TestRealtimeConn_RTC8a_ExplicitAuthorizeWhileConnected(0xc000bf7040)
	/home/runner/work/ably-go/ably-go/ably/realtime_conn_spec_integration_test.go:3088 +0x125
testing.tRunner(0xc000bf7040, 0xd56200)
	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1486 +0x725
FAIL	github.com/ably/ably-go/ably	701.964s
?   	github.com/ably/ably-go/ably/internal/ablyutil	[no test files]
?   	github.com/ably/ably-go/ablytest	[no test files]
?   	github.com/ably/ably-go/examples	[no test files]
?   	github.com/ably/ably-go/examples/realtime/presence	[no test files]
?   	github.com/ably/ably-go/examples/realtime/pub-sub	[no test files]
?   	github.com/ably/ably-go/examples/rest/history	[no test files]
?   	github.com/ably/ably-go/examples/rest/presence	[no test files]
?   	github.com/ably/ably-go/examples/rest/publish	[no test files]
?   	github.com/ably/ably-go/examples/rest/stats	[no test files]
?   	github.com/ably/ably-go/examples/rest/status	[no test files]
?   	github.com/ably/ably-go/scripts/errors	[no test files]
FAIL
```

**Comment by sacOO7** [comment]
Internal link to gateway error related discussion -> https://ably-real-time.slack.com/archives/C030C5YLY/p1699224411576189

**Comment by sacOO7** [comment]
Fixed as a part of https://github.com/ably/ably-go/pull/621/commits/e383770ac1b40ae05fc937a143ecdf1df8e80a51
