### ISSUE TITLE
failed assertions in `TestPresenceHistory_Direction_RSP4b2`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#577]
In [this integration test run](https://github.com/ably/ably-go/actions/runs/3838265654/jobs/6534820595#step:6:612) (JSON, Go 1.19):

```
=== RUN   TestPresenceHistory_Direction_RSP4b2
=== RUN   TestPresenceHistory_Direction_RSP4b2/direction=backwards
    rest_presence_spec_integration_test.go:87: 
        	Error Trace:	rest_presence_spec_integration_test.go:87
        	Error:      	Should be true
        	Test:       	TestPresenceHistory_Direction_RSP4b2/direction=backwards
=== RUN   TestPresenceHistory_Direction_RSP4b2/direction=forwards
    rest_presence_spec_integration_test.go:87: 
        	Error Trace:	rest_presence_spec_integration_test.go:87
        	Error:      	Should be true
        	Test:       	TestPresenceHistory_Direction_RSP4b2/direction=forwards
--- FAIL: TestPresenceHistory_Direction_RSP4b2 (90.41s)
    --- FAIL: TestPresenceHistory_Direction_RSP4b2/direction=backwards (45.70s)
    --- FAIL: TestPresenceHistory_Direction_RSP4b2/direction=forwards (44.71s)
```

**Comment by QuintinWillison** [comment]
Different failure, with panic, in [this integration test run](https://github.com/ably/ably-go/actions/runs/3838265654/jobs/6536180233#step:6:606) (msgpack, Go 1.18):

```
=== RUN   TestPresenceHistory_RSP4_RSP4b3
=== RUN   TestPresenceHistory_RSP4_RSP4b3/limit=2
    rest_presence_spec_integration_test.go:43: 
        	Error Trace:	rest_presence_spec_integration_test.go:43
        	Error:      	Should be true
        	Test:       	TestPresenceHistory_RSP4_RSP4b3/limit=2
=== RUN   TestPresenceHistory_RSP4_RSP4b3/limit=3
=== RUN   TestPresenceHistory_RSP4_RSP4b3/limit=20
--- FAIL: TestPresenceHistory_RSP4_RSP4b3 (78.20s)
    --- FAIL: TestPresenceHistory_RSP4_RSP4b3/limit=2 (49.07s)
    --- PASS: TestPresenceHistory_RSP4_RSP4b3/limit=3 (16.64s)
    --- PASS: TestPresenceHistory_RSP4_RSP4b3/limit=20 (12.49s)
=== RUN   TestPresenceHistory_Direction_RSP4b2
=== RUN   TestPresenceHistory_Direction_RSP4b2/direction=backwards
--- FAIL: TestPresenceHistory_Direction_RSP4b2 (30.15s)
    --- FAIL: TestPresenceHistory_Direction_RSP4b2/direction=backwards (30.15s)
panic: Gateway Timeout [recovered]
	panic: Gateway Timeout

goroutine 3541459 [running]:
testing.tRunner.func1.2({0xc71640, 0xc000d95e30})
	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1392 +0x5d2
panic({0xc71640, 0xc000d95e30})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:844 +0x258
github.com/ably/ably-go/ablytest.MustSandbox(0x51400000003?)
	/home/runner/work/ably-go/ably-go/ablytest/sandbox.go:126 +0x72
github.com/ably/ably-go/ablytest.NewREST({0x0, 0x0, 0x0})
	/home/runner/work/ably-go/ably-go/ablytest/sandbox.go:115 +0x52
github.com/ably/ably-go/ably_test.TestPresenceHistory_Direction_RSP4b2.func1(0xc000e71860)
	/home/runner/work/ably-go/ably-go/ably/rest_presence_spec_integration_test.go:65 +0x52
testing.tRunner(0xc000e71860, 0xc0009d8120)
	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1486 +0x725
FAIL	github.com/ably/ably-go/ably	977.578s
?   	github.com/ably/ably-go/ably/internal/ablyutil	[no test files]
?   	github.com/ably/ably-go/ablytest	[no test files]
?   	github.com/ably/ably-go/examples	[no test files]
?   	github.com/ably/ably-go/examples/realtime/presence	[no test files]
?   	github.com/ably/ably-go/examples/realtime/pub-sub	[no test files]
?   	github.com/ably/ably-go/examples/rest/history	[no test files]
?   	github.com/ably/ably-go/examples/rest/presence	[no test files]
?   	github.com/ably/ably-go/examples/rest/publish	[no test files]
?   	github.com/ably/ably-go/examples/rest/stats	[no test files]
?   	github.com/ably/ably-go/examples/rest/status	[no test files]
?   	github.com/ably/ably-go/scripts/errors	[no test files]
FAIL
```

**Comment by sacOO7** [comment]
Internal link to gateway error related discussion -> https://ably-real-time.slack.com/archives/C030C5YLY/p1699224411576189

**Comment by sacOO7** [comment]
Fixed as a part of https://github.com/ably/ably-go/pull/621/commits/e383770ac1b40ae05fc937a143ecdf1df8e80a51
